apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-skill-up
  labels:                   
    app: kubernetes-skill-up-api
spec:
  replicas: 2               
  selector:
    matchLabels:
      app: kubernetes-skill-up-api
  template:
    metadata:
      labels:
        app: kubernetes-skill-up-api
    spec:
      containers:
        - name: kubernetes-skill-up-api
          image: gaziwani/kubernetes-skill-up-api   
          ports:
            - containerPort: 3000                   
          env:
            - name: NODE_ENV
              value: "production"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name         
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5               
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10                
            periodSeconds: 20
